export const TEST = 'TEST';
export type TEST = typeof TEST;

export const SET_GAMEWEEK = 'SET_GAMEWEEK';
export type SET_GAMEWEEK = typeof SET_GAMEWEEK;

export const SET_TEAM = 'SET_TEAM';
export type SET_TEAM = typeof SET_TEAM;

export const SET_TEAMS = 'SET_TEAMS';
export type SET_TEAMS = typeof SET_TEAMS;

export const SET_LEAGUE = 'SET_LEAGUE';
export type SET_LEAGUE = typeof SET_LEAGUE;

export const SET_DIFFERENTIALS = 'SET_DIFFERENTIALS';
export type SET_DIFFERENTIALS = typeof SET_DIFFERENTIALS;

export const RECEIVE_EVENT_STATUS = 'RECEIVE_EVENT_STATUS';
export type RECEIVE_EVENT_STATUS = typeof RECEIVE_EVENT_STATUS;

export const RECEIVE_BOOTSTRAPSTATIC = 'RECEIVE_BOOTSTRAPSTATIC';
export type RECEIVE_BOOTSTRAPSTATIC = typeof RECEIVE_BOOTSTRAPSTATIC;

export const RECEIVE_ENTRY = 'RECEIVE_ENTRY';
export type RECEIVE_ENTRY = typeof RECEIVE_ENTRY;

export const RECEIVE_FIXTURES = 'RECEIVE_FIXTURES';
export type RECEIVE_FIXTURES = typeof RECEIVE_FIXTURES;

export const RECEIVE_PICKS = 'RECEIVE_PICKS';
export type RECEIVE_PICKS = typeof RECEIVE_PICKS;

export const RECEIVE_LIVE = 'RECEIVE_LIVE';
export type RECEIVE_LIVE = typeof RECEIVE_LIVE;

export const RECEIVE_EVENT = 'RECEIVE_EVENT';
export type RECEIVE_EVENT = typeof RECEIVE_EVENT;

export const RECEIVE_PROCESSED_PLAYERS = 'RECEIVE_PROCESSED_PLAYERS';
export type RECEIVE_PROCESSED_PLAYERS = typeof RECEIVE_PROCESSED_PLAYERS;

export const RECEIVE_LEAGUE_FIXTURES = 'RECEIVE_LEAGUE_FIXTURES';
export type RECEIVE_LEAGUE_FIXTURES = typeof RECEIVE_LEAGUE_FIXTURES;

export const RECEIVE_STANDINGS_H2H = 'RECEIVE_STANDINGS_H2H';
export type RECEIVE_STANDINGS_H2H = typeof RECEIVE_STANDINGS_H2H;

export const TAB_SELECT = 'TAB_SELECT';
export type TAB_SELECT = typeof TAB_SELECT;
